import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import test from 'node:test';
const url=source=>'data:text/javascript;base64,'+Buffer.from(source).toString('base64');
const compile=source=>url(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
test('catalog lifecycle, collection rename, visibility, ordering and upload authorization',async()=>{
 const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));
 globalThis.catalogTestAccess='owner';globalThis.catalogTestDb={prepare(sql){let values=[];return {bind(...v){values=v;return this},async all(){return {results:sqlite.prepare(sql).all(...values)}},async first(){return sqlite.prepare(sql).get(...values)},async run(){return sqlite.prepare(sql).run(...values)}}},async batch(statements){sqlite.exec('BEGIN');try{const results=await Promise.all(statements.map(s=>s.run()));sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
 const catalog=url(fs.readFileSync('public/catalog.mjs','utf8'));const validation=compile(fs.readFileSync('db/catalog-validation.ts','utf8'));
 const products=compile(fs.readFileSync('db/products.ts','utf8').replace("'../public/catalog.mjs'",JSON.stringify(catalog)).replace("import {bagDb} from './bag';","const bagDb=()=>globalThis.catalogTestDb;"));
 const apiSource=fs.readFileSync('app/api/admin/route.ts','utf8').replace("'../../../public/catalog.mjs'",JSON.stringify(catalog)).replace("'../../../db/products'",JSON.stringify(products)).replace("'../../../db/catalog-validation'",JSON.stringify(validation)).replace("import {ownerAccess} from '../../owner';","const ownerAccess=async()=>globalThis.catalogTestAccess;").replace("import {bagDb} from '../../../db/bag';","const bagDb=()=>globalThis.catalogTestDb;");
 const api=await import(compile(apiSource));const {getProducts,getCollectionDetails}=await import(products);
 const post=(data,origin='https://example.com')=>api.POST(new Request('https://example.com/api/admin',{method:'POST',headers:{origin},body:JSON.stringify(data)}));
 assert.equal((await getProducts()).length,7);
 assert.equal((await post({action:'create_collection',name:'Chapter 2'})).status,200);
 assert.equal((await post({action:'create_collection',name:'chapter 2'})).status,409);
 const piece={action:'create_product',name:'Test piece',description:'Test description',priceCents:5500,collection:'Chapter 2',type:'Shirts',color:'Black',image:'https://example.com/front.png',backImage:'',stockStatus:'in_stock',sizes:{XS:0,S:0,M:2,L:0,XL:0,XXL:0},sortOrder:4};
 assert.equal((await post(piece)).status,200);assert.equal((await getProducts()).length,7);assert.equal((await getProducts(true)).length,8);
 let saved=(await getProducts(true)).find(p=>p.name==='Test piece');assert.equal(saved.visibility,'draft');assert.equal(saved.sizes.M,2);
 assert.equal((await post({...piece,action:'update_product',id:saved.id,visibility:'published'})).status,200);assert.equal((await getProducts()).length,8);assert.equal((await getProducts()).at(-1).id,saved.id);
 assert.equal((await post({action:'update_collection',originalName:'Chapter 2',name:'Second collection',cover:'https://example.com/cover.png',featured:true})).status,200);
 assert.equal((await getProducts()).find(p=>p.id===saved.id).collection,'Second collection');assert.equal((await getCollectionDetails()).filter(c=>c.featured).length,1);
 assert.equal((await post({...piece,action:'update_product',id:saved.id,collection:'Second collection',visibility:'archived'})).status,200);assert.equal((await getProducts()).length,7);assert.equal((await getProducts(true)).length,8);
 assert.equal((await post({...piece,image:'javascript:alert(1)'})).status,400);
 assert.equal((await post(piece,'https://other.example')).status,403);
 globalThis.catalogTestAccess='anonymous';assert.equal((await post(piece)).status,401);
 const stored=new Map();globalThis.catalogTestEnv={BUCKET:{async put(key,bytes,opts){stored.set(key,{body:bytes,httpMetadata:opts.httpMetadata})},async get(key){return stored.get(key)}}};
 const upload=await import(compile(fs.readFileSync('app/api/admin/upload/route.ts','utf8').replace("import {env} from 'cloudflare:workers';","const env=globalThis.catalogTestEnv;").replace("import {ownerAccess} from '../../../owner';","const ownerAccess=async()=>globalThis.catalogTestAccess;")));
 const request=bytes=>new Request('https://example.com/api/admin/upload',{method:'POST',headers:{origin:'https://example.com'},body:bytes});
 assert.equal((await upload.POST(request('bad'))).status,403);globalThis.catalogTestAccess='owner';assert.equal((await upload.POST(request('<svg></svg>'))).status,400);assert.equal((await upload.POST(request(new Uint8Array(5*1024*1024+1)))).status,413);
 const png=Uint8Array.from([137,80,78,71,13,10,26,10]);const uploaded=await upload.POST(request(png));assert.equal(uploaded.status,200);const mediaUrl=(await uploaded.json()).url;assert.match(mediaUrl,/^\/media\//);assert.equal(stored.size,1);
 const media=await import(compile(fs.readFileSync('app/media/[id]/route.ts','utf8').replace("import {env} from 'cloudflare:workers';","const env=globalThis.catalogTestEnv;").replace("import {ownerAccess} from '../../owner';","const ownerAccess=async()=>globalThis.catalogTestAccess;").replace("'../../../db/products'",JSON.stringify(products))));
 globalThis.catalogTestAccess='anonymous';assert.equal((await media.GET(new Request('https://example.com'+mediaUrl))).status,404);globalThis.catalogTestAccess='owner';assert.equal((await media.GET(new Request('https://example.com'+mediaUrl))).status,200);
 sqlite.close();
});
