import {getProducts} from '../../../db/products';
import {pieces,productPrice,productStock,demoSizes} from '../../../public/catalog.mjs';
import {page,escape as e} from '../../../site/pages';
export async function GET(request:Request){
 let products;try{products=await getProducts();}catch{return new Response("Catalog temporarily unavailable. Please try again.",{status:503});}
 const slug=new URL(request.url).pathname.split('/').filter(Boolean).at(-1);const p=products.find(p=>p.id===slug);
 if(!p)return new Response(page('Piece not found','This piece is not in the Frilix catalog.','<section class="bag-page"><h1>Piece not found.</h1><a href="/#collection">Explore the collection</a></section>','/bag-common.mjs'),{status:404,headers:{'Content-Type':'text/html'}});
 const body=`<section class="product-page" data-product="${e(p.id)}"><a class="breadcrumb" href="/#collection">← ${e(p.collection)}</a><div class="pdp-grid"><div id="piece-viewer"></div><div class="pdp-copy"><p class="eyebrow">${e(p.collection)}</p><h1>${e(p.name)}</h1><p>${e(p.color)}</p><strong class="pdp-price">${productPrice(p)} <small>USD</small></strong><span class="stock-label" data-stock="${p.stockStatus}">${productStock(p)}</span><p>${e(p.description)}</p><form id="add-to-bag"><fieldset><legend>Select a size <span>Demo sizing</span></legend><div class="size-options">${demoSizes.map(size=>`<label><input type="radio" name="size" value="${size}" required ${p.stockStatus!=='in_stock'||p.sizes[size]===0?'disabled':''} aria-label="${size}${p.sizes[size]===0?' — sold out':''}"><span>${size}</span></label>`).join('')}</div><p class="size-stock-hint">Crossed-out sizes are unavailable. Stock is checked again when you add to bag.</p></fieldset><details class="size-guide"><summary>Size & fit information</summary><p>XS–XXL are example size options for this demo. Garment measurements, fit notes and available sizes will be confirmed before launch.</p></details><button class="button red" type="submit" ${p.stockStatus!=='in_stock'?'disabled':''}>${p.stockStatus==='in_stock'?'ADD TO BAG':productStock(p).toUpperCase()}</button><p id="product-feedback" role="status" aria-live="polite"></p></form><a class="text-link" href="/bag">VIEW YOUR BAG ↗</a><p class="detail-note">Demo prices, sizes and availability. No orders or payments are accepted.</p></div></div></section>`;
 return new Response(page(p.name,p.description,body,'/product.mjs'),{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'}});
}
